---
driver:
  name: vagrant
  vm_hostname: default-hostname.example.com

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: centos-7.3
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
  - recipe[hosts_file::default]
  attributes: {}
