---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: centos-7.2
  run_list:
  - recipe[yum]

suites:
- name: default
  run_list:
  - recipe[hosts_file::default]
  attributes: {}
