name 'hosts_file'
maintainer 'Heavy Water Operations, LLC.'
maintainer_email 'helpdesk@heavywater.io'
license 'Apache-2.0'
description 'Provides managed hosts file'
source_url        'https://github.com/hw-cookbooks/hosts_file'
issues_url        'https://github.com/hw-cookbooks/hosts_file/issues'
version '0.2.2'
